#!/usr/bin/env bash
# Phase 2-A.2 Step 4b — synthetic 32bpc goldens generator (driver).
#
# Reads tests/goldens/v1.4.0-ae2025/manifest.toml, walks every frame
# entry, and produces a matching SMDP v2 32bpc {in,out}.raw pair under
# tests/goldens/v1.6.0-32bpc/. The input is the v1.4.0 8/16bpc dump
# promoted to f32, the output is whatever smooth_core::process<
# PF_PixelFloat> produces — that algorithm is the reference per
# docs/PHASE_2A_GPU_RFC.md §3.2.6, no AE round trip required.
#
# This script is idempotent: re-running rebuilds the suite from scratch.
# It does NOT touch the v1.4.0-ae2025 directory.
#
# Usage:
#   tests/synthesize_32bpc_goldens.sh
set -uo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC_SUITE="$ROOT/tests/goldens/v1.4.0-ae2025"
DST_SUITE="$ROOT/tests/goldens/v1.6.0-32bpc"
SDK="$ROOT/references/AfterEffectsSDK_25.6_61_win/ae25.6_61.64bit.AfterEffectsSDK"
RUST_CRATE="$ROOT/rust/smooth_core"
RUST_LIB="$RUST_CRATE/target/universal/release/libsmooth_core.a"
BIN="$ROOT/tests/synth_32bpc"

if [ ! -f "$SRC_SUITE/manifest.toml" ]; then
    echo "missing $SRC_SUITE/manifest.toml — run Phase 2-A.2 Step 3 first" >&2
    exit 1
fi

echo "==> verify v1.4.0 fixtures (per-file SHA256)"
"$ROOT/tests/fetch_goldens.sh" v1.4.0-ae2025 || {
    echo "v1.4.0 integrity check failed; aborting"
    exit 1
}

echo "==> build Rust smooth_core (universal)"
"$RUST_CRATE/build-universal.sh" >/dev/null || { echo "cargo build failed"; exit 1; }

# Capture is always serial so the goldens are deterministic across reruns.
# The PARALLEL=1 regression run still goes through the rayon strip-parallel
# code path; frame 135 will exhibit a small f32 boundary residual that
# regression_test.cpp accepts as NEAR-ID under its local-Mac threshold
# (f32_diff_pct < 0.01% && max_f32_abs <= 0.125 — translated from the
# 8/16bpc rule). The tighter f32_abs <= 1e-5 figure documented in
# manifest.toml's cross_platform_policy is the Mac↔Win compare-time
# bound (Step 5), enforced separately and not by this script. Letting
# the operator override SMOOTH_PARALLEL here would defeat the
# determinism guarantee, so we deliberately do NOT honour it
# from the environment.
SMOOTH_PARALLEL=0

echo "==> build synth_32bpc tool (SMOOTH_PARALLEL=$SMOOTH_PARALLEL — serial for deterministic capture)"
clang++ -std=c++17 -O2 \
    -DSMOOTH_PARALLEL=$SMOOTH_PARALLEL \
    -I"$SDK/Examples/Headers" \
    -I"$SDK/Examples/Headers/SP" \
    -I"$SDK/Examples/Util" \
    -I"$RUST_CRATE/include" \
    -I"$ROOT" \
    "$ROOT/tests/synth_32bpc.cpp" \
    "$ROOT/util.cpp" \
    "$RUST_LIB" \
    -o "$BIN" || { echo "synth_32bpc build failed"; exit 1; }

mkdir -p "$DST_SUITE"
# Wipe stale .raw fixtures so leftover frames from older runs cannot
# pollute the SHA256 manifest. Leave manifest.toml alone (rebuilt below).
find "$DST_SUITE" -maxdepth 1 -name 'frame_*.raw' -delete

echo "==> generate 32bpc fixtures"
# Walk frames from the v1.4.0 manifest. Keeps frame numbering identical
# so manifest entries line up 1:1 across the two suites.
list_v140_frames() {
    python3 - "$SRC_SUITE/manifest.toml" <<'PY'
import sys, tomllib
with open(sys.argv[1], "rb") as f:
    m = tomllib.load(f)
for entry in m.get("frames", []):
    print(entry["in_file"])
PY
}

while IFS= read -r in_file; do
    [ -n "$in_file" ] || continue
    "$BIN" "$SRC_SUITE/$in_file" "$DST_SUITE" || {
        echo "synth_32bpc failed on $in_file" >&2
        exit 2
    }
done < <(list_v140_frames)

echo "==> regenerate manifest.toml from synthesized fixtures"
python3 - "$DST_SUITE" <<'PY'
import os, struct, hashlib, sys
DST = sys.argv[1]

def parse(p):
    with open(p, "rb") as f: hdr = f.read(64)
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for c in iter(lambda: f.read(65536), b""): h.update(c)
    return dict(
        version=struct.unpack_from("<I", hdr, 4)[0],
        width=struct.unpack_from("<I", hdr, 8)[0],
        height=struct.unpack_from("<I", hdr, 12)[0],
        bpc=struct.unpack_from("<I", hdr, 16)[0],
        rowbytes=struct.unpack_from("<I", hdr, 20)[0],
        frame_n=struct.unpack_from("<I", hdr, 28)[0],
        line_weight=struct.unpack_from("<f", hdr, 36)[0],
        white=struct.unpack_from("<I", hdr, 40)[0],
        range_f32=struct.unpack_from("<f", hdr, 44)[0],
        sha256=h.hexdigest(),
        size=os.path.getsize(p),
    )

frames = {}
for fname in sorted(os.listdir(DST)):
    if not fname.endswith(".raw"): continue
    meta = parse(os.path.join(DST, fname))
    role = "in" if "_in.raw" in fname else "out"
    frames.setdefault(meta["frame_n"], {})[role] = (fname, meta)

manifest_path = os.path.join(DST, "manifest.toml")
with open(manifest_path, "w") as out:
    out.write('# Phase 2-A.2 Step 4b: synthetic 32bpc goldens.\n')
    out.write('#\n')
    out.write('# Generated by tests/synthesize_32bpc_goldens.sh from the\n')
    out.write('# tests/goldens/v1.4.0-ae2025/ inputs (8/16bpc) by promoting\n')
    out.write('# pixels to f32 and running smooth_core::process<PF_PixelFloat>\n')
    out.write('# directly. The CPU 32bpc implementation IS the reference per\n')
    out.write('# docs/PHASE_2A_GPU_RFC.md §3.2.6, so the regression check is\n')
    out.write('# really "does the algorithm stay deterministic across builds\n')
    out.write('# and platforms?" — not "does it match an independent oracle?".\n')
    out.write('# That ground truth was already established in Phase 1 (8/16bpc\n')
    out.write('# vs AE-driven goldens) and 2-A.2 Step 1 (overbright/NaN unit\n')
    out.write('# tests). To re-generate, run tests/synthesize_32bpc_goldens.sh.\n')
    out.write('\n')
    out.write('schema_version = 1\n\n')
    out.write('[suite]\n')
    out.write('name = "v1.6.0-32bpc"\n')
    out.write('description = "Synthetic 32bpc goldens derived from v1.4.0-ae2025 inputs."\n')
    out.write('capture_source_platform = "synthesize_32bpc_goldens.sh (smooth_core CPU 32bpc)"\n')
    out.write('capture_date = "2026-05-03"\n')
    out.write('smooth_version = "1.5.0-dev (Phase 2-A.2 Step 4b)"\n')
    out.write('ae_version = "n/a (no AE round trip)"\n')
    out.write('sdk_version = "25.6_61"\n')
    out.write('artifact_url = ""\n')
    out.write('artifact_sha256 = ""\n\n')
    out.write('[suite.mac_reference_policy]\n')
    out.write('# Mac CPU bit-identical: the reference IS the algorithm, so a\n')
    out.write('# difference here means smooth_core regressed or rayon\n')
    out.write('# scheduling drifted in a way that survives strip-parallel\n')
    out.write('# stability assumptions. Either way, hard fail.\n')
    out.write('kind = "identical"\n\n')
    out.write('[suite.cross_platform_policy]\n')
    out.write('# Mac vs Win f32 rounding can differ in the LSBs even for the\n')
    out.write('# same algorithm; 1e-5 absolute is generous (~14-bit precision\n')
    out.write('# in [0,1]) and matches the RFC §3.2.6 recommendation.\n')
    out.write('kind = "near-id"\n')
    out.write('metric = "f32_abs"\n')
    out.write('max_abs = 1e-5\n\n')
    for n in sorted(frames.keys()):
        pair = frames[n]
        in_meta  = pair["in"][1]
        out_meta = pair["out"][1]
        out.write('[[frames]]\n')
        out.write(f'n = {n}\n')
        out.write(f'width  = {in_meta["width"]}\n')
        out.write(f'height = {in_meta["height"]}\n')
        out.write(f'bpc    = {in_meta["bpc"]}\n')
        out.write(f'rowbytes = {in_meta["rowbytes"]}\n')
        out.write(f'range_f32 = {in_meta["range_f32"]:.7g}\n')
        out.write(f'line_weight = {in_meta["line_weight"]:.6g}\n')
        out.write(f'white  = {bool(in_meta["white"]).__repr__().lower()}\n')
        out.write(f'in_file  = "{pair["in"][0]}"\n')
        out.write(f'out_file = "{pair["out"][0]}"\n')
        out.write(f'in_sha256  = "{in_meta["sha256"]}"\n')
        out.write(f'out_sha256 = "{out_meta["sha256"]}"\n')
        out.write(f'in_size  = {in_meta["size"]}\n')
        out.write(f'out_size = {out_meta["size"]}\n\n')
print(f"wrote {manifest_path}")
PY

echo "==> verify generated suite"
"$ROOT/tests/fetch_goldens.sh" v1.6.0-32bpc

echo "done. tests/run_regression.sh v1.6.0-32bpc to confirm 14/14 IDENTICAL."
