// Phase 2-C FFI surface. Incrementally expanded per step.
// Generated by hand (no cbindgen yet). Matches rust/smooth_core/src/lib.rs.
//
// ============================================================================
// CALLER CONTRACT (applies to every function below)
// ============================================================================
//
//   Buffer layout
//   -------------
//   * `in_ptr` / `out_ptr` point to pixel buffers in AE's PF_Pixel8 /
//     PF_Pixel16 layout: { alpha, red, green, blue } in memory order, 4 or
//     8 bytes per pixel, row-major.
//   * `rowbytes` is the byte stride per row. May be larger than
//     `logical_width * sizeof(Pixel)` (AE sometimes pads for alignment).
//   * The allocated size MUST be at least `rowbytes * height` bytes, addressed
//     via `in_ptr[j * rowbytes + i * sizeof(Pixel)]`.
//
//   Alignment
//   ---------
//   * `in_ptr` and `out_ptr` must be aligned for their element type
//     (4-byte for the _u8 entries, 8-byte for the _u16 entries). AE's pixel
//     world pointers satisfy this; passing an arbitrary byte offset does not.
//
//   Aliasing
//   --------
//   * For `smooth_core_process_row_range_*`, `in_ptr` and `out_ptr` must NOT
//     point to overlapping memory. `in_ptr` is read during scan/blend;
//     `out_ptr` is written. Supplying the same pointer for both is undefined.
//   * For `smooth_core_preprocess_*`, only `in_ptr` is used (in place).
//
//   Threading
//   ---------
//   * All entry points are reentrant: you may call them from multiple threads
//     concurrently as long as each call uses its own buffers and its own
//     `smooth_row_range_args_t` value.
//   * With `parallel = 1`, the callee itself uses rayon internally; callers
//     must not add their own outer thread pool (doing so just oversubscribes
//     the CPU and gives no speedup).
//
// ============================================================================

#ifndef SMOOTH_CORE_FFI_H_
#define SMOOTH_CORE_FFI_H_

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

/* Linkage probe.
 * Upper 16 bits = major version (2), lower 16 bits = FFI revision.
 * Bump the low 16 bits whenever any of the structs below changes layout. */
uint32_t smooth_core_version(void);

/* Human-readable build identity, captured at Rust crate build time.
 *
 * Format: "<crate-semver>+<git-short-sha>[+dirty]"
 *   e.g.  "0.1.0+0c5b06d"       (clean)
 *         "0.1.0+0c5b06d+dirty" (uncommitted changes present at build)
 *         "0.1.0+unknown"       (git unavailable, e.g. tarball build)
 *
 * The returned pointer is a static null-terminated ASCII string valid for the
 * lifetime of the loaded plugin; do NOT free it.
 *
 * Intended use: the C++ plugin surface this in the Effect Controls panel and
 * the About dialog so a human can tell at a glance which build is loaded.
 * This is the primary defence against "false-success" stale-cache builds
 * (Phase 2-D post-mortem documents one such incident). */
const char *smooth_core_build_id(void);

/* Step 2: preProcess.
 *
 * Scans `in_ptr` once and:
 *   (a) if `is_white_trans != 0`, replaces every pixel whose RGB (alpha is
 *       ignored) matches the "white key" (0xFF for u8, 0x8000 for u16) with
 *       the null pixel (all channels zero) in place;
 *   (b) fills `*bbox_out` with the bounding box of non-white, non-zero-alpha
 *       pixels, using the convention:
 *         top    = first row with any such pixel                         (else 0)
 *         left   = minimum column across all rows with any such pixel    (else 0)
 *         right  = (max column + 1), or 1 if none found
 *         bottom = (max row    + 1), or 1 if none found
 */
typedef struct {
    int32_t top;
    int32_t left;
    int32_t right;
    int32_t bottom;
} smooth_bbox_t;

void smooth_core_preprocess_u8 (void *in_ptr, int32_t rowbytes, int32_t height,
                                int32_t is_white_trans, smooth_bbox_t *bbox_out);
void smooth_core_preprocess_u16(void *in_ptr, int32_t rowbytes, int32_t height,
                                int32_t is_white_trans, smooth_bbox_t *bbox_out);

/* Phase 2-A.2 Step 1: 32bpc (PF_PixelFloat) variant. Same contract as the
 * u8/u16 entries except the buffer is interpreted as { f32 alpha, red,
 * green, blue } (16 bytes per pixel). White key = (1.0, 1.0, 1.0, 1.0). */
void smooth_core_preprocess_f32(void *in_ptr, int32_t rowbytes, int32_t height,
                                int32_t is_white_trans, smooth_bbox_t *bbox_out);

/* Step 3: process_row_range.
 *
 * One call performs the full scan + blend pass for rows [j_start, j_end) x
 * cols [i_start, i_end), reading from `in_ptr` and writing to `out_ptr`.
 *
 * The caller is expected to have already:
 *   1. run smooth_core_preprocess_* (so `in_ptr` has white -> null_pixel, if
 *      requested);
 *   2. copied `in_ptr` into `out_ptr` (the scan pass only overwrites edge
 *      pixels; interior pixels must already be present in `out_ptr`).
 * `smooth_core.h::smooth_core::process<T>` performs both steps so the AE
 * plugin path does not need to.
 *
 * Step 4: parallelism is internal to Rust.
 *   parallel = 0  => serial (byte-exact reproduction of Phase 1 serial baseline).
 *   parallel != 0 => rayon strip-parallel; currently treated as 1.
 *                    NOTE: Phase 1's SEAM_HALO=0 boundary residual (~30 bytes
 *                    per HD 16bpc frame, under the regression NEAR-ID tolerance)
 *                    is intentionally preserved. `out_ptr` is written
 *                    concurrently from strip workers; the boundary residual is
 *                    the only observable symptom.
 */
typedef struct {
    void    *in_ptr;
    void    *out_ptr;
    int32_t  width;          /* rowbytes / sizeof(Pixel); padded width */
    int32_t  logical_width;  /* actual image column count (<= width) */
    int32_t  height;
    int32_t  rowbytes;
    uint32_t range;
    float    line_weight;
    int32_t  j_start;        /* row range, half-open */
    int32_t  j_end;
    int32_t  i_start;        /* column range, half-open */
    int32_t  i_end;
    int32_t  parallel;       /* 0 = serial, != 0 = rayon strip-parallel */
} smooth_row_range_args_t;

void smooth_core_process_row_range_u8 (const smooth_row_range_args_t *args);
void smooth_core_process_row_range_u16(const smooth_row_range_args_t *args);

/* Phase 2-A.2 Step 1: 32bpc variant. Identical to smooth_row_range_args_t
 * except `range` is f32 (in AE's 0.0..1.0 domain, scaled by max_value=1.0
 * already on the C++ side via Params::range_f32). */
typedef struct {
    void    *in_ptr;
    void    *out_ptr;
    int32_t  width;
    int32_t  logical_width;
    int32_t  height;
    int32_t  rowbytes;
    float    range;          /* f32 instead of u32 */
    float    line_weight;
    int32_t  j_start;
    int32_t  j_end;
    int32_t  i_start;
    int32_t  i_end;
    int32_t  parallel;
} smooth_row_range_args_f32_t;

void smooth_core_process_row_range_f32(const smooth_row_range_args_f32_t *args);

#ifdef __cplusplus
}
#endif

#endif /* SMOOTH_CORE_FFI_H_ */
