// Phase 2-C FFI surface. Incrementally expanded per step.
// Generated by hand (no cbindgen yet). Matches rust/smooth_core/src/lib.rs.

#ifndef SMOOTH_CORE_FFI_H_
#define SMOOTH_CORE_FFI_H_

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

/* Linkage probe.
 * Upper 16 bits = major version (2), lower 16 bits = FFI revision. */
uint32_t smooth_core_version(void);

/* Step 2: preProcess.
 * bbox semantics: see smooth_core.h / Rust pre_process. */
typedef struct {
    int32_t top;
    int32_t left;
    int32_t right;
    int32_t bottom;
} smooth_bbox_t;

void smooth_core_preprocess_u8 (void *in_ptr, int32_t rowbytes, int32_t height,
                                int32_t is_white_trans, smooth_bbox_t *bbox_out);
void smooth_core_preprocess_u16(void *in_ptr, int32_t rowbytes, int32_t height,
                                int32_t is_white_trans, smooth_bbox_t *bbox_out);

/* Step 3: process_row_range.
 * One call handles the full scan+blend pass for rows [j_start, j_end) x cols [i_start, i_end).
 *
 * Step 4: parallelism is now internal to Rust.
 *   parallel = 0  => serial (byte-exact reproduction of Phase 1 serial baseline).
 *   parallel = 1  => rayon strip-parallel (Phase 1 SEAM_HALO=0 boundary behaviour,
 *                    row-block strips scaled to rayon::current_num_threads()). */
typedef struct {
    void    *in_ptr;
    void    *out_ptr;
    int32_t  width;          /* rowbytes / sizeof(Pixel) */
    int32_t  logical_width;
    int32_t  height;
    int32_t  rowbytes;
    uint32_t range;
    float    line_weight;
    int32_t  j_start;
    int32_t  j_end;
    int32_t  i_start;
    int32_t  i_end;
    int32_t  parallel;       /* 0 = serial, 1 = rayon strip-parallel */
} smooth_row_range_args_t;

void smooth_core_process_row_range_u8 (const smooth_row_range_args_t *args);
void smooth_core_process_row_range_u16(const smooth_row_range_args_t *args);

#ifdef __cplusplus
}
#endif

#endif /* SMOOTH_CORE_FFI_H_ */
